
data:
  content_dir: "/kaggle/input/datasets/awsaf49/coco-2017-dataset/coco2017/train2017"     # Path to MS COCO train images
  style_path:  "data/styles/mosaic.jpg" # Path to style image
  validation_dir: "data/validation"   # Path to validation samples
  image_size:   256                       # Input/output resolution
  batch_size:   44
  num_workers:  8

model:
  # Norm layer used inside ResidualBlock, Downsample, Upsample.
  # "batch" → BatchNorm2d
  # "instance" → InstanceNorm2d
  norm_type: "instance"

training:
  epochs:        1
  learning_rate: 1.0e-3

  content_weight: 5.0
  style_weight:   5.0e+4
  tv_weight:      0.0

  scheduler:
    type: "cosine"
    eta_min: 1.0e-6

  checkpoint_dir: "models/checkpoints"
  final_model_path: "models/fast-nst.pth"

wandb:
  project:    "configure-nst"
  run_name:   "kaggle-run"
  log_every_n_steps: 50
